name: Android Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Set up JDK (adjust Java version if needed)
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      # Cache Gradle dependencies
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Grant execute permission for gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # Set up Android SDK and Emulator
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 30   # Adjust the API level if needed
          target: google_apis # This ensures the correct system image
          arch: x86_64
          emulator: true
          script: true

      # Create AVD (Android Virtual Device)
      - name: Create Emulator
        run: |
          echo "y" | avdmanager create avd -n test -k "system-images;android-30;google_apis;x86_64"

      # Start Emulator and wait for it to boot
      - name: Start Emulator
        run: |
          emulator -avd test -no-window -no-snapshot -noaudio -no-boot-anim &
          adb wait-for-device
          adb shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done; input keyevent 82'
        shell: bash

      # Build the project using Gradle
      - name: Build with Gradle
        run: ./gradlew build

      # Run Instrumentation Tests (UI tests)
      - name: Run Instrumentation Tests
        run: ./gradlew connectedAndroidTest
        env:
          ADB_INSTALL_TIMEOUT: 20 # Increase if emulator startup takes time

      # Run Unit Tests
      - name: Run Unit Tests
        run: ./gradlew test

      # Stop the Emulator
      - name: Stop Emulator
        run: adb -s emulator-5554 emu kill
