name: Android Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'  # Specify the distribution

      - name: Install Android SDK
        run: |
          mkdir -p $HOME/Android/Sdk
          cd $HOME/Android/Sdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip
          unzip commandlinetools-linux-7302050_latest.zip
          yes | sdkmanager --sdk_root=$HOME/Android/Sdk --install "cmdline-tools;latest"
          yes | sdkmanager --sdk_root=$HOME/Android/Sdk --install "platform-tools" "platforms;android-30" "system-images;android-30;google_apis;x86"

      - name: Set up Android Emulator
        run: |
          yes | $HOME/Android/Sdk/cmdline-tools/latest/bin/avdmanager create avd -n test -k "system-images;android-30;google_apis;x86" --device "pixel" --force
          nohup $HOME/Android/Sdk/emulator/emulator -avd test -no-window &

      - name: Wait for Emulator
        run: |
          adb wait-for-device
          adb shell input keyevent 82  # Unlock the emulator

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run Instrumentation Tests
        run: ./gradlew connectedAndroidTest

      - name: Run Unit Tests
        run: ./gradlew test
