name: Android Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:  # This allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '17'  # Change according to your project's Java version

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Cache Gradle packages
        uses: actions/cache@v3  # Updated to the latest version
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Install Gradle 8.9
        run: |
          wget https://services.gradle.org/distributions/gradle-8.9-bin.zip
          unzip gradle-8.9-bin.zip -d /opt/gradle
          echo "/opt/gradle/gradle-8.9/bin" >> $GITHUB_PATH  # Add Gradle to the PATH
          rm gradle-8.9-bin.zip
      - name: Build with Gradle
        run: gradle build  --warning-mode all

      - name: Run Unit Tests
        run: gradle test  # Use the installed Gradle
      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: build/reports/tests/test
