name: Android Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Install Android SDK and Emulator
        run: |
          echo "Installing Android SDK and Emulator..."
          mkdir -p $HOME/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip
          unzip commandlinetools-linux-7302050_latest.zip -d $HOME/android-sdk/cmdline-tools
          rm commandlinetools-linux-7302050_latest.zip
          mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest

          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator:$PATH

          yes | sdkmanager --sdk_root=$ANDROID_HOME --install "platform-tools" "emulator" "system-images;android-30;google_apis;x86"

      - name: Create and Start Emulator
        run: |
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator:$PATH
          
          yes | avdmanager create avd -n test -k "system-images;android-30;google_apis;x86" --device "pixel"
          nohup emulator -avd test -no-window &

      - name: Wait for Emulator
        run: |
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator:$PATH
          
          adb wait-for-device
          adb shell input keyevent 82  # Unlock the emulator
          adb shell "while [[ \$(getprop sys.boot_completed) -ne 1 ]]; do sleep 1; done"
          sleep 10  # Additional wait time

      - name: Check ADB Connection
        run: |
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator:$PATH
          adb devices

      - name: Run Instrumentation Tests
        run: ./gradlew connectedAndroidTest --warning-mode all

      - name: Run Unit Tests
        run: ./gradlew test --warning-mode all
